language: rust

matrix:
  include:
    - rust: nightly
      env: FEATURES='' ARGS='--release'
    - rust: nightly
      env: FEATURES='semihosting'
    - rust: nightly
      env: FEATURES='bkpt'

before_script:
  - rustup target add thumbv7em-none-eabihf
    # - rustup component add clippy

script:
  # - cargo clippy
  - "cargo build --target thumbv7em-none-eabihf --features \"$FEATURES\" $ARGS"

notifications:
  email: false

branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Uncomment this to enable building pull requests.
    - master
